### ISSUE TITLE
Check runs gets added to the wrong check suite

### ISSUE THREAD

**Issue by aslafy-z** [reviewdog/reviewdog#403] opened 2020-01-02 15:50 UTC
I implemented a linter action for yamllint using reviewdog, see #402.

I still have one problem with it, see https://github.com/aslafy-z/reviewdog-yamllint-action/pull/1. The resulting check gets added into the wrong check suite.

![2019-12-31-194324_798x284_scrot](https://user-images.githubusercontent.com/8191198/71630877-d9dfc180-2c05-11ea-8ed0-6a2387a4f9be.png)
![2019-12-31-194553_429x189_scrot](https://user-images.githubusercontent.com/8191198/71630962-42c73980-2c06-11ea-868c-980c17c15de4.png)

I've been looking around and found https://github.community/t5/GitHub-Actions/Github-Actions-Status-Checks-created-on-incorrect-Check-Suite-Id/m-p/36180#M2466 which refer to the same problem.

Any issues on your side?

**Comment by haya14busa** [comment] 2020-01-03 10:00
Thanks for the report! AFAIU, it's a github issue as you pasted a link.
I'm not aware of any workaround nor issue on reviewdog side.

**Comment by ogizanagi** [comment] 2020-10-23 10:37
Hi 👋 
Can't we use the Github checks API to identify the right check suite?
[This action](https://github.com/shyim/junit-report-annotations-action/blob/3d2e5374f2b13e70f6f3209a21adfdbc42c466ae/index.js#L26-L32) accepts a jobName as input and uses it to resolve the check to which the annotations would be reported.

**Comment by haya14busa** [comment] 2020-10-24 08:41
Unfortunately no. It means it re-uses the existing check run for github action job and the check result / status will be conflicted. (tested #797)

**Comment by rmacklin** [comment] 2021-02-03 20:48
@haya14busa Sorry for the dumb question, but can you explain what you expected to see in https://github.com/reviewdog/reviewdog/pull/797/checks compared to what is actually showing there? I'm trying to understand what the root issue is here (and if it has possibly been fixed on GitHub's end since you last posted).

**Comment by ruudk** [comment] 2021-08-05 07:30
I have the same problem.

@rmacklin The problem is, that if you have multiple workflows like this:
<img width="323" alt="Screenshot 2021-08-05 at 09 28 37@2x" src="https://user-images.githubusercontent.com/104180/128309602-798c819b-aa8a-4627-8fe5-5aa280ee2324.png">
the reported checks by reviewdog are put on the first (?) workflow instead of the workflow that initiated Reviewdog.

So in my case, Reviewdog runs in `Continuous Integration` but it's checks are reported under `PHPStan`. 

This is extremely annoying when you have protected branches with required checks. Those will all say in oragen saying "waiting for required check".

**Comment by austinpray-mixpanel** [comment] 2022-07-26 16:42
This hasn't been fixed on GitHub's side yet. I opened a support ticket with them 🤷.

Latest case: the flake8 check is generated by the python linting workflow, but it falls under our comment outdated diff workflow.
![image (2)](https://user-images.githubusercontent.com/71290498/181062731-ed39cc07-a312-4fb3-b6b8-bea98aea0e09.png)
![image (1)](https://user-images.githubusercontent.com/71290498/181062739-4a369e7e-ae0e-4caa-a06f-3c35f14b0fe7.png)

**Comment by austinpray-mixpanel** [comment] 2022-10-04 14:20
For posterity: here's the response I got from support a while ago

> It appears the flake8 test is being created manually using the [checks API](https://docs.github.com/en/rest/checks/runs#create-a-check-run). In general, you can only create 1 [check suite](https://docs.github.com/en/rest/guides/getting-started-with-the-checks-api#about-check-suites) against a particular commit, but GitHub Actions is an exception where you can have multiple check suites for a particular commit -one for every workflow run against that commit.
>
>The problem is that if you manually create a check run, it can't be attached to a specific check suite. The community post below discusses this in more detail here:
>
>https://github.com/orgs/community/discussions/24616#discussioncomment-3244677
>
>The Actions team has received feedback on this and there are discussions on having a way to attach a manually created check to a particular checksuite. I have added your voice to the discussion. You will, however, not be able to do this at the moment, sorry.

**Comment by mheap** [comment] 2022-12-15 12:40
Would it be possible to add an environment variable to disable using the checks API and fall back to annotations like it does when running on a fork?
 
https://github.com/reviewdog/reviewdog/blob/98f2b8bb53a0f34b3407480c06ab8eb8506f03d4/cienv/github_actions.go#L107-L117

This would enable inline annotations using this code:

https://github.com/reviewdog/reviewdog/blob/98f2b8bb53a0f34b3407480c06ab8eb8506f03d4/cmd/reviewdog/doghouse.go#L194-L200

This would allow Actions to report failures in the correct group

**Comment by krystof-k** [comment] 2023-08-01 11:33
Is there any news regarding this after 3.5 years? Really driving me crazy…

**Closed** 2024-01-11 10:42 UTC
Labels: github-bug
