### ISSUE TITLE
GitHub-PR-check reports to the wrong job when using concurrency

### ISSUE THREAD

**Issue by jdgirald** [reviewdog/reviewdog#1297] opened 2022-09-27 22:03 UTC
I have an action with concurrency enabled to ensure that only a single job will run at a time. However, the reporter creates the checks report in the canceled job instead of the current job.

Reporter: GitHub Checks (-reporter=github-pr-check)
command: `reviewdog -name="Apex Tests ($TARGET)" -f=rdjsonl -reporter=github-pr-check -filter-mode=nofilter`

current job:
![image](https://user-images.githubusercontent.com/45671148/192643829-2f77c5b7-5fb2-4f4d-bedc-a3cb138ebd9a.png)

Canceled job:
![image](https://user-images.githubusercontent.com/45671148/192644030-fe4238cd-d98f-4542-9ba1-84c83b5683f1.png)

In this case, the github checks `Apex Tests` should be presented in the current job and not the canceled one.

![image](https://user-images.githubusercontent.com/45671148/192646060-f16133b4-8a0e-4ccb-b5c1-62977838e5c3.png)

**Comment by austinpray-mixpanel** [comment] 2022-10-04 14:18
I'm pretty sure this is https://github.com/reviewdog/reviewdog/issues/403

**Comment by javierjulio** [comment] 2023-03-27 16:09
This can be closed as its a duplicate of #403.

**Closed** 2023-05-03 16:44 UTC
