### ISSUE TITLE
reviewdog doesn't respect error level of checkstyle report

### ISSUE THREAD

**Issue by code-schreiber** [reviewdog/reviewdog#486] opened 2020-02-28 19:51 UTC
Let me start first by saying thanks for opening up more possibilities when reviewing code with such a powerful tool 🥇 

I haven't managed to get reviewdog to work perfectly with [detekt](https://arturbosch.github.io/detekt/) checkstyle reports of a Kotlin project. These reports already have a severity (error or warning) but reviewdog reports all of them as errors with Github checks.
My current hack so that warnings don't block a PR is to set the `level` of reviewdog to only `warning`.

`reviewdog -f=checkstyle -reporter=github-check -level=warning...`

Here a report example

```xml
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
<file name="/Users/user/Project/app/src/main/kotlin/Class.kt">
	<error line="10" column="5" severity="error" message="Variable names should match the pattern: [a-z][A-Za-z0-9]*" source="detekt.VariableNaming" />
	<error line="14" column="36" severity="warning" message="This expression contains a magic number. Consider defining it to a well named constant." source="detekt.MagicNumber" />
</file>
</checkstyle>
```

Any ideas of what can be done to improve this behavior?

**Comment by haya14busa** [comment] 2020-05-07 17:02
Duplicate of #343

**Closed by haya14busa** 2020-05-07 17:02 UTC
